/** Modell-Vorschläge pro Marke – für Datalist im Formular */
export const MODELLE_PRO_MARKE: Record<string, string[]> = {
  'Audi': [
    'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8',
    'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q6 e-tron', 'Q7', 'Q8', 'Q8 e-tron',
    'TT', 'TTS', 'TT RS',
    'R8',
    'e-tron', 'e-tron GT', 'e-tron S',
    'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'RS Q3', 'RS Q8',
    'S3', 'S4', 'S5', 'S6', 'S7', 'S8',
    'Allroad',
  ],
  'BMW': [
    '1er', '2er', '3er', '4er', '5er', '6er', '7er', '8er',
    'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM',
    'Z3', 'Z4',
    'M2', 'M3', 'M4', 'M5', 'M6', 'M8',
    'M135i', 'M235i', 'M340i', 'M440i', 'M550i',
    'iX', 'iX1', 'iX2', 'iX3', 'i3', 'i4', 'i5', 'i7',
    '116i', '118i', '120i', '316i', '318i', '320i', '330i', '530i', '730i',
  ],
  'Mercedes-Benz': [
    'A-Klasse', 'B-Klasse', 'C-Klasse', 'E-Klasse', 'S-Klasse',
    'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS',
    'G-Klasse', 'GT', 'SL', 'SLC',
    'AMG GT', 'C 43', 'C 63', 'E 43', 'E 53', 'E 63', 'G 63',
    'EQA', 'EQB', 'EQC', 'EQE', 'EQS',
    'Sprinter', 'Vito', 'V-Klasse', 'Citan',
    'ML', 'GL',
  ],
  'Volkswagen': [
    'Golf', 'Golf Plus', 'Golf Sportsvan', 'Golf Variant',
    'Polo', 'Polo GTI',
    'Passat', 'Passat Variant', 'Passat Alltrack',
    'Tiguan', 'Tiguan Allspace',
    'Touareg', 'Touran',
    'T-Roc', 'T-Cross',
    'ID.3', 'ID.4', 'ID.5', 'ID.7',
    'Arteon', 'Arteon Shooting Brake',
    'Up', 'e-up',
    'Sharan', 'Caddy', 'Transporter', 'Multivan',
    'Phaeton', 'Amarok',
    'Scirocco', 'Eos', 'CC',
    'Beetle', 'Lupo', 'Fox',
  ],
  'Opel': [
    'Astra', 'Astra Sports Tourer',
    'Insignia', 'Insignia Sports Tourer', 'Insignia Country Tourer',
    'Corsa', 'Corsa-e',
    'Mokka', 'Mokka-e',
    'Crossland', 'Grandland', 'Grandland X',
    'Zafira', 'Zafira Life',
    'Vectra', 'Meriva', 'Agila',
    'Cascada', 'Ampera', 'Ampera-e',
    'Adam', 'Karl', 'Combo',
    'Movano', 'Vivaro',
  ],
  'Ford': [
    'Focus', 'Focus Turnier',
    'Fiesta',
    'Mondeo', 'Mondeo Turnier',
    'Kuga',
    'Puma', 'EcoSport',
    'Explorer', 'Bronco',
    'Mustang', 'Mustang Mach-E',
    'S-Max', 'Galaxy', 'B-Max', 'C-Max',
    'Ka', 'Ka+',
    'Edge', 'Ranger',
    'Transit', 'Transit Custom', 'Transit Connect',
  ],
  'Toyota': [
    'Aygo', 'Aygo X',
    'Yaris', 'Yaris Cross',
    'Corolla', 'Corolla Touring Sports',
    'C-HR',
    'Camry',
    'RAV4',
    'Highlander',
    'Land Cruiser', 'Land Cruiser 300',
    'Prius', 'Prius+',
    'Auris', 'Auris Touring Sports',
    'Avensis', 'Avensis Touring Sports',
    'Proace', 'Proace City',
    'GR86', 'GR Yaris', 'GR Supra',
    'bZ4X',
    'Hilux',
  ],
  'Honda': [
    'Jazz', 'Jazz e:HEV',
    'Civic', 'Civic Type R',
    'CR-V',
    'HR-V',
    'ZR-V',
    'Accord',
    'Legend',
    'FR-V', 'CR-Z',
    'e', 'e:Ny1',
    'Stream', 'Insight',
  ],
  'Hyundai': [
    'i10', 'i20', 'i20 N', 'i30', 'i30 N', 'i40',
    'Tucson',
    'Santa Fe',
    'Kona', 'Kona Electric',
    'Ioniq', 'Ioniq 5', 'Ioniq 6',
    'Nexo',
    'Bayon',
    'ix20', 'ix35', 'ix55',
    'Staria',
  ],
  'Kia': [
    'Picanto',
    'Rio',
    'Ceed', 'ProCeed', 'Ceed Sportswagon',
    'Stinger',
    'Niro', 'Niro EV',
    'Sportage',
    'Sorento',
    'Stonic',
    'XCeed',
    'EV6',
    'Carnival',
    'Soul',
    'Telluride',
  ],
  'Skoda': [
    'Fabia', 'Fabia Combi',
    'Octavia', 'Octavia Combi', 'Octavia RS',
    'Superb', 'Superb Combi',
    'Kodiaq',
    'Karoq',
    'Kamiq',
    'Scala',
    'Enyaq', 'Enyaq Coupé',
    'Citigo', 'Citigo-e',
    'Rapid',
    'Yeti',
  ],
  'Seat': [
    'Ibiza',
    'Leon', 'Leon ST', 'Leon Sportstourer',
    'Ateca',
    'Tarraco',
    'Arona',
    'Toledo',
    'Alhambra',
    'Exeo',
    'Mii', 'Mii electric',
  ],
  'Renault': [
    'Clio', 'Clio Grandtour',
    'Megane', 'Megane Grandtour', 'Megane E-Tech',
    'Laguna', 'Laguna Grandtour',
    'Kadjar',
    'Captur',
    'Koleos',
    'Arkana',
    'Austral',
    'Espace',
    'Scenic', 'Grand Scenic',
    'Twingo', 'Twingo Electric',
    'Zoe',
    'Kangoo', 'Kangoo E-Tech',
    'Talisman', 'Talisman Grandtour',
    'Sandero', 'Sandero Stepway',
  ],
  'Peugeot': [
    '107', '108',
    '205', '206', '207', '208', 'e-208',
    '301', '305', '306', '307', '308', '308 SW',
    '405', '406', '407', '408',
    '505', '508', '508 SW',
    '2008', 'e-2008',
    '3008',
    '5008',
    'Partner', 'Traveller', 'Expert',
    'RCZ',
    'Rifter',
  ],
  'Citroën': [
    'C1', 'C2', 'C3', 'C3 Aircross', 'ë-C3',
    'C4', 'C4 Cactus', 'ë-C4',
    'C5', 'C5 Aircross', 'C5 X',
    'C6', 'C8',
    'Berlingo', 'ë-Berlingo',
    'Jumpy', 'Spacetourer',
    'DS3', 'DS4', 'DS5',
    'Xsara', 'Xsara Picasso',
    'Saxo',
  ],
  'Fiat': [
    '500', '500C', '500X', '500L', '500e',
    'Punto', 'Grande Punto', 'Punto Evo',
    'Bravo', 'Brava', 'Stilo',
    'Tipo', 'Tipo SW',
    'Panda', 'Panda Cross',
    'Doblo', 'Fiorino',
    'Ducato', 'Scudo',
    '124 Spider',
  ],
  'Nissan': [
    'Micra',
    'Note',
    'Juke',
    'Qashqai',
    'X-Trail',
    'Murano',
    'Leaf',
    'Ariya',
    '350Z', '370Z',
    'GT-R',
    'Navara',
    'Patrol',
    'Primera', 'Almera', 'Pulsar',
    'NV200',
  ],
  'Mazda': [
    'Mazda2', 'Mazda3', 'Mazda6',
    'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-80',
    'MX-5',
    'MX-30',
    'RX-8',
    '2', '3', '6',
  ],
  'Mitsubishi': [
    'Colt',
    'Lancer', 'Lancer Sportback',
    'Eclipse Cross',
    'ASX',
    'Outlander', 'Outlander PHEV',
    'Pajero', 'Pajero Sport',
    'L200',
    'Galant',
    'Space Star',
  ],
  'Dacia': [
    'Sandero', 'Sandero Stepway',
    'Logan', 'Logan MCV',
    'Duster',
    'Lodgy',
    'Dokker',
    'Spring',
    'Jogger',
    'Bigster',
  ],
  'Alfa Romeo': [
    'Giulia',
    'Giulietta',
    'Stelvio',
    'Tonale',
    '147', '156', '159',
    'Mito',
    'Brera',
    'Spider',
    'GTV',
    '4C',
  ],
  'Volvo': [
    'S40', 'S60', 'S90',
    'V40', 'V40 Cross Country',
    'V50', 'V60', 'V60 Cross Country',
    'V70', 'V90', 'V90 Cross Country',
    'XC40', 'XC60', 'XC70', 'XC90',
    'C30', 'C40', 'C70',
    'EX30', 'EX90',
  ],
  'Land Rover': [
    'Defender',
    'Discovery', 'Discovery Sport',
    'Freelander',
    'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar',
  ],
  'Porsche': [
    '911', 'Boxster', 'Cayman',
    'Cayenne', 'Cayenne Coupe',
    'Macan',
    'Panamera', 'Panamera Sport Turismo',
    'Taycan', 'Taycan Cross Turismo',
  ],
  'Mini': [
    'Mini', 'Mini Clubman', 'Mini Cabriolet', 'Mini Paceman', 'Mini Countryman', 'Mini Coupe',
    'John Cooper Works',
    'Electric',
    'Cooper', 'Cooper S', 'Cooper SE',
    'One', 'One D',
  ],
  'Subaru': [
    'Impreza', 'Impreza STI',
    'Legacy', 'Legacy Outback',
    'Forester',
    'XV',
    'Outback',
    'BRZ',
    'Levorg',
    'Solterra',
  ],
  'Suzuki': [
    'Swift', 'Swift Sport',
    'Baleno',
    'Celerio',
    'Ignis',
    'Vitara', 'Grand Vitara',
    'SX4', 'SX4 S-Cross',
    'Jimny',
    'Alto',
    'Splash',
    'Across',
  ],
  'Jeep': [
    'Renegade',
    'Compass',
    'Cherokee', 'Grand Cherokee', 'Grand Cherokee 4xe',
    'Wrangler', 'Wrangler Unlimited',
    'Gladiator',
    'Commander',
    'Avenger',
  ],
  'Cupra': [
    'Formentor',
    'Born',
    'Ateca',
    'Leon', 'Leon Sportstourer',
    'Terramar',
  ],
  'Tesla': [
    'Model 3',
    'Model S',
    'Model X',
    'Model Y',
    'Cybertruck',
    'Roadster',
  ],
  'Polestar': [
    'Polestar 1',
    'Polestar 2',
    'Polestar 3',
    'Polestar 4',
  ],
  'BYD': [
    'Atto 3',
    'Han',
    'Tang',
    'Seal',
    'Dolphin',
    'Sea Lion',
  ],
  'MG': [
    'ZS', 'ZS EV',
    'HS',
    'MG4',
    'MG5',
    'Marvel R',
    'EHS',
  ],
  'Smart': [
    'Fortwo', 'Fortwo Cabrio', 'Fortwo Electric Drive',
    'Forfour', 'Forfour Electric Drive',
    '#1', '#3',
  ],
  'Jaguar': [
    'XE', 'XF', 'XF Sportbrake', 'XJ',
    'E-Pace', 'F-Pace', 'I-Pace',
    'F-Type',
    'XK',
  ],
  'Lexus': [
    'CT 200h',
    'IS', 'ES', 'GS', 'LS',
    'NX', 'RX', 'UX',
    'LC', 'RC',
    'LBX',
    'RZ',
  ],
  'Saab': [
    '9-3', '9-3 Cabrio', '9-3 SportCombi',
    '9-5', '9-5 SportCombi',
    '9-7X',
  ],
  'DS Automobiles': [
    'DS 3', 'DS 3 Crossback', 'DS 3 E-Tense',
    'DS 4', 'DS 4 Crossback',
    'DS 5',
    'DS 7', 'DS 7 Crossback',
    'DS 9',
  ],
  'Infiniti': ['Q30', 'Q50', 'Q60', 'QX30', 'QX50', 'QX70', 'QX80', 'FX', 'EX'],
  'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80', 'GV60'],
  'Rolls-Royce': ['Ghost', 'Phantom', 'Wraith', 'Dawn', 'Cullinan', 'Spectre'],
  'Bentley': ['Continental GT', 'Continental GTC', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  'Maserati': ['Ghibli', 'Levante', 'Quattroporte', 'Grecale', 'GranTurismo'],
  'Ferrari': ['458', '488', 'Roma', 'Portofino', 'SF90', '812', 'F8', 'Purosangue', 'California'],
  'Lamborghini': ['Huracán', 'Urus', 'Revuelto'],
  'Chevrolet': ['Aveo', 'Cruze', 'Camaro', 'Corvette', 'Captiva', 'Trax', 'Blazer', 'Tahoe', 'Silverado'],
  'Chrysler': ['300C', 'PT Cruiser', 'Voyager', 'Pacifica'],
  'Dodge': ['Challenger', 'Charger', 'Durango', 'Journey', 'Ram 1500'],
  'Alpine': ['A110', 'A290'],
  'Aston Martin': ['Vantage', 'DB11', 'DBX', 'DBS', 'DB9'],
  'Isuzu': ['D-Max', 'Trooper', 'Rodeo'],
  'Lancia': ['Ypsilon', 'Delta', 'Musa', 'Phedra', 'Voyager'],
  'SsangYong': ['Tivoli', 'Korando', 'Musso', 'Rexton', 'Rodius', 'Actyon'],
  'Sonstige': [],
}
